-- MySQL Script generated by MySQL Workbench
-- Thu Oct  6 13:52:24 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`pytania`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pytania` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pytanie` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`odpowiedzi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`odpowiedzi` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `odpowiedz` LONGTEXT NULL,
  `poprawna` TINYINT NULL,
  `pytania_id` INT NOT NULL,
  PRIMARY KEY (`id`, `pytania_id`),
  INDEX `fk_odpowiedzi_pytania_idx` (`pytania_id` ASC),
  CONSTRAINT `fk_odpowiedzi_pytania`
    FOREIGN KEY (`pytania_id`)
    REFERENCES `mydb`.`pytania` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
